# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43e68256ea446d3f823fd923aebb837d48a54e795ea9ccdeacc24f9b95c06727918457b767b1db2de6b65dbca5d90db3d3a8c5ee80d41c1661c8142247d98840

test:
  secret_key_base: a03e5063d45935189da77b389e3d69d5db03085f7dfb65632203443b7fc02027a6f2c6dc398fd9031c5bbe2d4fafc4c91e1b5ef3b4bf984fd24756aa2169c689

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
